### ISSUE TITLE
error pushing logs

### ISSUE THREAD

**Issue by nidheeshdas** [previousnext/k8s-aws-cloudwatchlogs#3]
i'm getting 
```
time="2018-07-16T15:47:28Z" level=error msg="Failed to put log events" errorCode=InvalidSequenceTokenException logGroupName=kube-system logStreamName=kube-ingress-aws-controller-776bbff9b6-cml7c-controller-9e524c9b138dbf75ed9ba1de596e7a0b020216d7b8789d3197d612b76061e369 message="The given sequenceToken is invalid. The next expected sequenceToken is: 49586203143724815170159453868388155161844879999285333506" origError="&lt;nil&gt;"

```

my daemonset.yaml

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aws-cloudwatchlogs
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: aws-cloudwatchlogs
    spec:
      containers:
      - name: k8s-aws-cloudwatchlogs
        image: previousnext/k8s-aws-cloudwatchlogs:2.0.3
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "AxxxxxxxxxxxxQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "vxxxxxxxxxxxxxxxxb"
        - name: REGION
          value: "ap-south-1"
        - name: AWS_REGION
          value: "ap-south-1"
        - name: KUBERNETES_CONTAINER_LOGS
          value: /var/log/containers
        resources:
          limits:
            cpu: 5m
            memory: 25Mi
          requests:
            cpu: 5m
            memory: 25Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers

```
